version: "3.9"

x-aws-vpc: ${VPC}
x-aws-cluster: ${CLUSTER}
x-aws-loadbalancer: ${LOAD_BALANCER}

services:
  gateway:
    image: $AWS_ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/gateway-jd:latest
    ports:
      - target: ${APP_PORT}
        x-aws-protocol: http
    environment:
      - APP_SERVICE_HOST=${APP_SERVICE_HOST}
      - APP_PORT=${APP_PORT}
    networks:
      - public
networks:
  public:
    external: true
    name: ${SG_PUBLIC}

x-aws-cloudformation:
  Resources:
    GatewayService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - ${SUBNET_ONE}
              - ${SUBNET_TWO}
    Gateway80TargetGroup:
      Properties:
        HealthCheckPath: /health
        Matcher:
          HttpCode: 200-499
    Gateway80Listener:
      Properties:
        Protocol: HTTPS
        Certificates:
          - CertificateArn: ${SSL_CERT}